export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
. "$HOME/.cargo/env"

if [ -f /opt/homebrew/etc/bash_completion ]; then source /opt/homebrew/etc/bash_completion; fi

export PATH="$PATH:/Users/kod/.cache/lm-studio/bin"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:/Users/kod/.pdtm/go/bin"
export PATH="$PATH:/Users/kod/.foundry/bin"
